data:
    train_data_path: ../data/train
    val_data_path: ../data/val
    num_workers: 36
    train_bs_per_device: 9
    val_bs_per_device: 4

model_name: rvq+conv
model:
    in_dim: 2
    in_freq: 192
    h_dims: [45,72,96,144,192,384] #[16,16,24,24,32,64]
    max_streams: 6
    backbone: conv
    kernel_size: [5,2]
    conv_depth: 1
    overlap: 4
    num_rvqs: 18
    group_size: 1
    codebook_size: 1024
    codebook_dim: 8
    l2norm: True
    win_len: 20
    hop_len: 5
    sr: 16000

loss:
    stft_weight: 1.0
    cm_weight: .25
    cb_weight: 1.0
    mel_weight: .25