data:
    train_data_path: ../data/train
    val_data_path: ../data/val
    num_workers: 36
    train_bs_per_device: 9
    val_bs_per_device: 4

model_name: csvq+conv
model:
    

loss:
    stft_weight: 1.0
    cm_weight: .25
    cb_weight: 1.0
    mel_weight: .25