data:
    train_data_path: ../../../data/dnscustom/processed_wav/train
    val_data_path: ../../../data/dnscustom/processed_wav/test
    num_workers: 36
    train_bs_per_device: 18
    val_bs_per_device: 6

model_name: csvq+conv
model:
    in_dim: 2
    in_freq: 192
    h_dims: [45,72,96,144,192,384] #[16,16,24,24,32,64]
    max_streams: 6
    kernel_size: [5,2]
    conv_depth: 1
    overlap: 4
    group_size: 3
    codebook_size: 1024
    codebook_dim: 8
    l2norm: True
    init_method: kmeans
    win_len: 20
    hop_len: 5
    sr: 16000

loss:
    stft_weight: 1.0
    cm_weight: .25
    cb_weight: 1.0
    mel_weight: .25