data:
    data_dir: "/root/autodl-tmp/data"
    in_freq: 192
    win_len: 20
    hop_len: 5
    sr: 16000

model:
    in_dim: 2
    in_freq: 192
    h_dims: [45,72,96,144,192,384]
    swin_depth: 2
    swin_heads: [3,6,12,24,24]
    window_size: 4
    mlp_ratio: 4.
    max_streams: 6
    overlap: 2
    num_vqs: 3
    proj_ratio: 1.
    codebook_size: 1024
    codebook_dims: [12]
    patch_size: [3,2]
    use_ema: False
    use_cosine_sim: True
    is_causal: False
    vq: "GVQ"
    fuse_net: "None"
    scalable: True
    mel_windows: [32,64,128,256,512,1024,2048]
    mel_bins: [5,10,20,40,80,160,320]
    win_len: 20
    hop_len: 5
    sr: 16000

discriminator:
    sample_rate: 16000
    rates: []
    periods: [2, 3, 5, 7, 11]
    fft_sizes: [2048, 1024, 512]
    bands:
        - [0.0, 0.1]
        - [0.1, 0.25]
        - [0.25, 0.5]
        - [0.5, 0.75]
        - [0.75, 1.0]

loss:
    recon_factor: 0.0
    commitment_factor: .25
    codebook_factor: 1.0
    reg_factor: 0.0
    mel_factor: 15.0
    gen_factor: 1.0
    feat_factor: 2.0