# data
data_name: DNS_CHALLENGE
normalization: mean_var

# model
model_name: csvq_codec
model_mode: scalable

csvq_codec: 
  ch_mult: 
  - 8
  - 8
  - 12
  - 12
  - 16
  - 32
  down_rate: 0.4
  num_groups: 6
  power_law: 1
  n_mels: 800
  num_RNN_layers: 12
  TCM_Dilation:
  - 1
  - 2
  - 4
  - 8
  codebook_size: 1024
  vq_commit: 1.0
  stft_consist: 1
  mel_factor: 0.25
  vq_factor: 0.25
  causal: True

  batch_size:
    train: 40
    test: 16
  shuffle:
    train: True
    test: False

  optimizer_name: Adam
  lr: 3.0e-4
  weight_decay: 0
  betas: [0.9,0.999]
  momentum: 0.9
  nesterov: True

  scheduler_name: ReduceLROnPlateau
  factor: 0.95
  patience: 2
  threshold: 1.0e-4
  min_lr: 1.0e-8
  
  num_epochs: 200

f_dims:
  - 201
  - 101
  - 51
  - 26
  - 13
  - 7
  
# dataset
stats:
  LIBRISPEECH:
    - [-0.00031031499383971095, -3.4487189992660205e-08]
    - [0.5290760397911072, 0.4847901165485382]
  DNS_CHALLENGE:
    - [-3.2371788165619364e-06, 1.0734881428220433e-08]
    - [0.6311184167861938, 0.6211439967155457]
raw_F: 201
train_T: 600

# experiment
num_workers: 4
init_seed: 0
num_experiments: 1
device: cuda
world_size: 1
resume_mode: 0
verbose: False
pivot_metric: PESQ
cuda_device: 0
plot_interval: 0.5
seed: 0

sr: 16000
win_length: 20
hop_length: 5

train_dur: 3
test_dur: 10

train_clips: 180000
test_clips: 1158

save_image: True
fixed_bitstream: 6









