# control  ######
control:
  loss_mode: 'base'
  num_clients: '100'
  active_rate: '0.1'
  data_split_mode: 'iid'
  local_epoch: '5'
  gm: '0'
# data
data_name: LIBRISPEECH
model_name: vqvae
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False